# Site settings
title: Yihui He blog
email: yihuihe@foxmail.com
description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://yihui-he.github.io"
blogurl: "http://yihui-he.github.io/blog"
#twitter_username: karpathy
github_username:  yihui-he

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
